apiVersion: apps/v1
kind: Deployment
metadata:
    name: tornado-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: tornado-app
    template:
        metadata:
            labels:
                app: tornado-app
        spec:
            containers:
                - name: python-container
                  image: us-central1-docker.pkg.dev/moaaz-461013/demo-repo/devops-app
                  ports:
                      - containerPort: 8000
                  env:
                      - name: REDIS_HOST
                        value: redis
                      - name: REDIS_PORT
                        value: '6379'
                      - name: REDIS_DB
                        value: '0'
---
apiVersion: v1
kind: Service
metadata:
    name: tornado-service
spec:
    selector:
        app: tornado-app
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8000
    type: NodePort
